'use server'

import { createClient } from '@/lib/supabase/server'
import { getBasicProductInfo } from '@/lib/dreamlove/soap'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

export interface ShippingAddress {
  name: string
  street: string
  city: string
  postalCode: string
  country: string
  phone: string
  email: string
}

export async function createOrder(shippingAddress: ShippingAddress) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  // Fetch cart items with product details
  const { data: cartItems } = await supabase
    .from('cart_items')
    .select('*, product:products(*), variant:product_variants(*)')
    .eq('user_id', user.id)

  if (!cartItems?.length) return { error: 'Cart is empty' }

  // Real-time stock validation — NEVER skip this
  for (const item of cartItems) {
    const product = item.product as { dreamlove_id: string; name: string }
    let stockInfo
    try {
      stockInfo = await getBasicProductInfo(product.dreamlove_id)
    } catch {
      return {
        error: `Could not verify stock for "${product.name}". Please try again.`,
      }
    }

    if (!stockInfo.available || stockInfo.stock < item.quantity) {
      return {
        error: `"${product.name}" is out of stock or has insufficient quantity.`,
        productId: product.dreamlove_id,
      }
    }
  }

  const subtotal = cartItems.reduce((sum, i) => {
    const product = i.product as { retail_price: number }
    return sum + product.retail_price * i.quantity
  }, 0)

  const shippingCost = 0 // TODO: implement shipping cost logic
  const total = subtotal + shippingCost

  // Create order — UUID generated by Supabase default
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .insert({
      user_id: user.id,
      status: 'pending',
      shipping_address: shippingAddress,
      subtotal: Math.round(subtotal * 100) / 100,
      shipping_cost: shippingCost,
      total: Math.round(total * 100) / 100,
      currency: 'EUR',
      payment_status: 'unpaid',
    })
    .select()
    .single()

  if (orderError || !order) {
    return { error: orderError?.message ?? 'Failed to create order' }
  }

  // Insert order items
  const orderItems = cartItems.map((i) => {
    const product = i.product as {
      id: string
      dreamlove_id: string
      name: string
      retail_price: number
      supplier_price: number
    }
    return {
      order_id: order.id,
      product_id: product.id,
      variant_id: i.variant_id ?? null,
      dreamlove_id: product.dreamlove_id,
      name: product.name,
      quantity: i.quantity,
      unit_price: product.retail_price,
      supplier_price: product.supplier_price,
      total_price: Math.round(product.retail_price * i.quantity * 100) / 100,
    }
  })

  const { error: itemsError } = await supabase.from('order_items').insert(orderItems)
  if (itemsError) {
    // Rollback order on item insert failure
    await supabase.from('orders').delete().eq('id', order.id)
    return { error: itemsError.message }
  }

  // Clear cart
  await supabase.from('cart_items').delete().eq('user_id', user.id)

  revalidatePath('/account/orders')
  return { success: true, orderId: order.id }
}

export async function redirectToPayment(orderId: string) {
  // TODO: integrate Stripe — create PaymentIntent and redirect to hosted checkout
  redirect(`/account/orders/${orderId}`)
}
